### ISSUE TITLE
Add CC box to Email

### ISSUE THREAD

**Issue by hkouns** [GSBCfamily/bvcms#8]
Originally submitted to TPS 1/21/14 as Request ID: 930

FEATURE REQUEST:
I love the ability to go to an organization and select email all ... it is so fast and simple.  However, often I need to send the email to one or two more people.  For instance, I am going to send an email to the ushers...but I want to copy the Pastor and Outreach Director.
This is relatively easily fixed by using the powerful Search Builder ... however it requires several steps.
I keep wishing that there was a CC box when drafting an email... similar to the way you have a CC box on the support email editor.

![bvcms_supportccbox](https://cloud.githubusercontent.com/assets/5140785/8572992/69037d16-255d-11e5-9af4-f0b8c1d06d55.png)

It would also allow the recipient to reply to more than one person.

I could envision it being implemented in one of two ways:
• Barebones: It is a simple text box for comma separated emails... no record is kept in BVCMS
• BVCMS Feel:  The box is actually a "Search Box" in which additional names could be added by typing partial first and last name (standard search process)  The email would then get recorded on the person's record.  However... if no record is found then it would default to treating it as a unrecorded email address.
![bvcms_emailccbox](https://cloud.githubusercontent.com/assets/5140785/8572998/6cdd32ba-255d-11e5-9b09-395aa52e1551.png)

Either way would work for me.

Thanks for the consideration.

**Comment by nehresma** [comment]
Hey Keith,

I don't actually have Windows or Visual Studio (I'm a Linux user).  I'll try and get a developer preview of Windows 10 with the express edition of Visual Studio running in a VM.  I'm new to .Net development too but I'll look into this.

**Comment by nehresma** [comment]
Doh!  Heath, not Keith.  I work with a Keith -- typo from habit.  Sorry.  Heh.

**Comment by hkouns** [comment]
No problem on the name ;-) I've learned to answer to just about anything.
I thought the email side might be a good place to start based on your experience with Squirrel Mail.

**Comment by hkouns** [comment]
@nehresma as I think more about this issue, there may actually be two cases... I don't know how much it really influences the work you have already done. 

1) Just adding another person for the email to goto... essentially adding them to the TO: field.  In this case we would certainly want it to be a person in the database so that it can be tracked on their record, etc.  For instance... We are sending an email to a bible Fellowship Class to invite them to a cookout  ... then we remember, we should invite the pastor as well. Currently we would need to add them to a tag...or run a query.   With this feature we could just goto the Org and email all members ... then add the pastor on the email page.  It would probably would be best to use the standard search/add dialog box. But could also use a process like on the Mission trip email page where you enter the email and it searches for the people record.

2) adding a person to the CC, in this case it would be nice to actually have this person CC'd on each email that goes out to the people in the TO : field.  This would enable the recipient to "reply-all" and reply to more than just the original sender of the email.  In this case, It would be nice to be able to include a "raw" email address.  For instance, if we send out an email to a mailing list about the budget... we could CC  "Finances@****.org".  Then way people could reply-all and respond to the finance team.

Note this is more for a "final" solution.. incremental progress in either direction would be great.

**Comment by nehresma** [comment]
Yep, both of those make sense.

**Comment by hkouns** [comment]
Is this the file you were looking for: https://github.com/bvcms/bvcms/blob/master/SqlScripts/BuildDb/Creating_dbo_EmailQueue.sql

**Comment by hkouns** [comment]
@nehresma once you have the basic structure in place... if you want to post a branch, I will pull sync to it and test.  thanks.

**Comment by hkouns** [comment]
Pull request (https://github.com/bvcms/bvcms/pull/75) for CC box only issued to BVCMS/Master.

Adding peopleIDs to "To:" field will be handled under a separate Issue#

**Comment by hkouns** [comment]
Combined with adding Recipients to TO field and submitted to BVCMS https://github.com/bvcms/bvcms/pull/86
